---
- name: Install Signal Desktop
  ansible.builtin.shell: flatpak install -y flathub {{ signal_flatpak_package }}
  args:
    executable: /bin/bash
  become: true
  register: signal_installation_result
  changed_when: "'Installing' in signal_installation_result.stdout"
  failed_when: "'error' in signal_installation_result.stderr"
