---
# ulauncher_role/tasks/main.yml
- name: Check if Ulauncher is already installed
  ansible.builtin.command: command -v ulauncher
  register: ulauncher_installed
  failed_when: false
  changed_when: false
  check_mode: false

- name: Install dependencies for Ulauncher
  ansible.builtin.dnf:
    name:
      - gtk3
      - python3
      - python3-pip
    state: present
  when: ulauncher_installed.rc != 0

- name: Install Ulauncher
  ansible.builtin.pip:
    name: ulauncher
    state: "{{ ulauncher_version }}"
  when: ulauncher_installed.rc != 0

- name: Create Ulauncher desktop entry
  ansible.builtin.template:
    src: ulauncher.desktop.j2
    dest: /usr/share/applications/ulauncher.desktop
    mode: '0644'
  when: ulauncher_installed.rc != 0
