---
- name: Check if linode-cli is already installed
  ansible.builtin.command: /usr/bin/pip3 list --format=freeze
  register: pip_list
  become: true
  become_user: jay
  changed_when: "'linode-cli' not in pip_list.stdout"

- name: Install linode-cli using pip
  ansible.builtin.pip:
    executable: /usr/bin/pip3
    state: present
    name: linode-cli
  become: true
  become_user: jay
  when: "'linode-cli' not in pip_list.stdout"
  tags: packages, linode, pip, python
