---
- name: Copy wallpaper file
  tags: gnome, gnome-wallpaper
  become: true
  ansible.builtin.copy:
    src: "{{ wallpaper_src }}"
    dest: "{{ wallpaper_dest }}"
    owner: root
    group: root
    mode: "0644"

- name: Set wallpaper
  tags: gnome, gnome-wallpaper
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ wallpaper_dest }}'"

- name: Set wallpaper position
  tags: gnome, gnome-wallpaper
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/background/picture-options
    value: "'zoom'"

- name: Copy lock screen background file
  tags: gnome, gnome-lockscreen
  become: true
  ansible.builtin.copy:
    src: "{{ lockscreen_src }}"
    dest: "{{ lockscreen_dest }}"
    owner: root
    group: root
    mode: "0644"

- name: Set lock screen background
  tags: gnome, gnome-lockscreen
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/picture-uri
    value: "'file://{{ lockscreen_dest }}'"

- name: Set lock screen background position
  tags: gnome, gnome-lockscreen
  become: true
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/picture-options
    value: "'zoom'"

- name: Check if GNOME Terminal is installed
  ansible.builtin.command: which gnome-terminal
  register: gnome_terminal_installed
  failed_when: gnome_terminal_installed.rc != 0
  changed_when: false
  ignore_errors: true
