- name: Uninstall Internet Explorer Playbook
  hosts: windows_hosts
  tasks:
    - name: Uninstall Internet Explorer
      win_shell: |
        Write-Output "Uninstalling Internet Explorer..."
        Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -like "Internet-Explorer-Optional*" } | Disable-WindowsOptionalFeature -Online -NoRestart -WarningAction SilentlyContinue | Out-Null
        Get-WindowsCapability -Online | Where-Object { $_.Name -like "Browser.InternetExplorer*" } | Remove-WindowsCapability -Online | Out-Null
      register: uninstall_ie_result

    - name: Display result of uninstallation
      debug:
        var: uninstall_ie_result
