- name: Uninstall Telnet Client Playbook
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Uninstall Telnet Client on Windows 10
      win_feature:
        name: "Telnet-Client"
        state: absent
      when: ansible_os_family == 'Windows' and ansible_distribution_major_version == '10'
