---
- name: Check if Packer is already installed
  ansible.builtin.command: packer --version
  register: packer_installed
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Download and install Packer
  when: packer_installed.rc != 0
  block:
    - name: Find latest Packer version
      ansible.builtin.uri:
        url: https://releases.hashicorp.com/packer/index.json
        method: GET
        return_content: true
      register: packer_releases
      when: packer_version is defined and packer_version == 'latest'

    - name: Set packer_version to latest
      ansible.builtin.set_fact:
        packer_version: "{{ (packer_releases.json | json_query('packer.versions.*.version') | sort | last) }}"
      when: packer_version == 'latest'

    - name: Install Packer binary
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: "0755"
        owner: root
        group: root
