---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if VSCode is already installed
  ansible.builtin.set_fact:
    vscode_installed: "'code' in ansible_facts.packages"

- name: Import Microsoft GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ vscode_repo_gpg_key }}"
  when: not vscode_installed is failed

- name: Add VSCode repository
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: "{{ vscode_repo_url }}"
    gpgcheck: true
    gpgkey: "{{ vscode_repo_gpg_key }}"
  when: not vscode_installed is failed

- name: Install VSCode
  ansible.builtin.package:
    name: "{{ vscode_package_name }}"
    state: present
  when: not vscode_installed is failed
