---
- name: Ensure wget and tar are installed
  dnf:
    name:
      - wget
      - tar
    state: present

- name: Check if Android Studio is already installed
  stat:
    path: "{{ android_studio_install_dir }}/android-studio"
  register: android_studio_installed

- block:
  - name: Download Android Studio tarball
    get_url:
      url: "{{ android_studio_download_url }}"
      dest: "/tmp/android-studio.tar.gz"
      mode: '0644'
    when: not android_studio_installed.stat.exists

  - name: Extract Android Studio tarball
    ansible.builtin.unarchive:
      src: "/tmp/android-studio.tar.gz"
      dest: "{{ android_studio_install_dir }}"
      remote_src: yes
      creates: "{{ android_studio_install_dir }}/android-studio"
    when: not android_studio_installed.stat.exists

  - name: Set Android Studio environment variables
    template:
      src: android_studio.sh.j2
      dest: /etc/profile.d/android_studio.sh

  when: not android_studio_installed.stat.exists