---
# tasks file for civu_cli

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Download civu CLI script
  ansible.builtin.get_url:
    url: https://civo.com/get
    dest: /tmp/civu_install.sh
    mode: '0755'
  become: true

- name: Install civu CLI
  ansible.builtin.shell:
    cmd: /tmp/civu_install.sh
    creates: /usr/local/bin/civo
  become: true
