---
- name: Check if Google Chrome is already installed
  ansible.builtin.yum:
    list: google-chrome-stable
  register: chrome_installed
  failed_when: "'google-chrome-stable' not in chrome_installed.results"
  changed_when: false
  ignore_errors: true

- name: Install Google Chrome
  ansible.builtin.yum:
    name: google-chrome-stable
  when: chrome_installed is failed

- name: Include Google Chrome extension tasks
  ansible.builtin.import_tasks: chrome_extensions.yml

- name: Include Google Chrome settings tasks
  ansible.builtin.import_tasks: chrome_settings.yml
