---
# tasks/main.yml
- name: Check if caffeine is installed
  ansible.builtin.yum:
    list: caffeine
  register: caffeine_installed
  failed_when: '"Installed Packages" not in caffeine_installed.results'
  changed_when: false

- name: Install caffeine
  ansible.builtin.yum:
    name: caffeine
    state: present
  when: caffeine_installed.results | length == 0
  tags:
    - packages
    - workstation-packages
    - caffeine
