# tasks/main.yml
- name: Import the Google Chrome repository key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ chrome_repo_key_url }}"

- name: Add Google Chrome repository
  ansible.builtin.yum_repository:
    name: google-chrome
    description: Google Chrome YUM repository
    baseurl: "{{ chrome_repo_baseurl }}"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ chrome_repo_key_url }}"

- name: Install Google Chrome
  ansible.builtin.yum:
    name: google-chrome-stable
    state: present
