- name: Ensure Firefox distribution directory exists on Rocky Linux
  ansible.builtin.file:
    path: "/usr/lib/firefox/distribution"
    state: directory
    mode: '0755'
  become: true

- name: Deploy Firefox policies for extension installation
  ansible.builtin.copy:
    src: "{{ role_path }}/files/firefox_policies_extensions.json"
    dest: "/usr/lib/firefox/distribution/extensions-policies.json"
    mode: '0644'
  become: true
