---
- name: Install KVM and other dependencies
  dnf:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-daemon-kvm
      - virt-install
      - bridge-utils
      - kubectl
    state: present
  register: package_installation
  changed_when: "'No package' not in package_installation.msg"

- name: Start and enable libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  when: package_installation is changed

- name: Check if Minikube is already installed
  stat:
    path: "{{ minikube_destination }}"
  register: minikube_stat

- name: Download Minikube
  get_url:
    url: "{{ minikube_url }}"
    dest: "{{ minikube_destination }}"
    mode: "{{ minikube_permissions }}"
  when: not minikube_stat.stat.exists

- name: Install Minikube
  command: minikube start --driver=kvm2
  become: yes
  become_user: "{{ user_name }}"
  when: not minikube_stat.stat.exists
