---
- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add HashiCorp YUM repository
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install Nomad
  ansible.builtin.yum:
    name: nomad
    state: present
