---
- name: Install KVM and other dependencies
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-daemon-kvm
      - virt-install
      - bridge-utils
      - kubectl
    state: present
  register: package_installation
  changed_when: package_installation.msg | default('') | search('No package') == 0
  notify: Start and enable libvirtd service

- name: Check if Minikube is already installed
  ansible.builtin.stat:
    path: "{{ minikube_destination }}"
  register: minikube_stat

- name: Download Minikube
  ansible.builtin.get_url:
    url: "{{ minikube_url }}"
    dest: "{{ minikube_destination }}"
    mode: "{{ minikube_permissions }}"
  when: not minikube_stat.stat.exists

- name: Install Minikube
  ansible.builtin.command:
    cmd: minikube start --driver=kvm2
  become: true
  become_user: "{{ user_name }}"
  when: not minikube_stat.stat.exists
  changed_when: false
