---
# spotify_setup/tasks/main.yml

- name: Add Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true
  changed_when: false

- name: Check if Spotify is already installed
  ansible.builtin.command: flatpak list | grep com.spotify.Client
  register: spotify_installed
  changed_when: false
  ignore_errors: true

- name: Install Spotify
  ansible.builtin.command: flatpak install -y flathub com.spotify.Client
  become: true
  when: spotify_installed.rc != 0
  changed_when: true # This task actually changes the state if Spotify is not installed, so it's appropriate to allow Ansible to handle change detection here.
