---
- name: Ensure Git is installed
  ansible.builtin.dnf:
    name: git
    state: present

- name: Set global Git configuration
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_config }}"
  loop_control:
    loop_var: item
