---
# defaults/main.yml
# Ensure there are no unnecessary blank lines

# tasks/main.yml
- name: Check if Conda is already installed
  ansible.builtin.command: "{{ conda_install_path }}/bin/conda --version"
  register: conda_version_check
  ignore_errors: true
  changed_when: false

- name: Download Conda installer script
  ansible.builtin.get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
    mode: '0755' # Set appropriate file permissions
  when: conda_version_check is failed

- name: Install Conda
  ansible.builtin.command: bash /tmp/miniconda.sh -b -p {{ conda_install_path }}
  args:
    creates: "{{ conda_install_path }}/bin/conda"
  when: conda_version_check is failed

- name: Ensure Conda is in PATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/conda.sh
    line: export PATH="{{ conda_install_path }}/bin:$PATH"
    create: true
    mode: '0644' # Set appropriate file permissions
  when: conda_version_check is failed
