---
# Default working path for Linux
working_path: /tmp/
virtualbox_package_name: VirtualBox-6.1
required_packages:
  - wget
  - dkms
  - kernel-devel
  - kernel-headers
  - make
  - gcc
virtualbox_repo_url: https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
virtualbox_repo_dest: /etc/yum.repos.d/virtualbox.repo
