---
# tasks file for ensuring Flathub repository is added and Telegram Desktop is installed
- name: Add Flathub repository
  ansible.builtin.command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    creates: /var/lib/flatpak/repo/flathub.trustedkeys.gpg

- name: Check if Telegram Desktop is installed
  ansible.builtin.command:
    cmd: flatpak list --app
  register: telegram_installed
  changed_when: false
  failed_when: "'org.telegram.desktop' not in telegram_installed.stdout"

- name: Install Telegram Desktop
  ansible.builtin.command:
    cmd: flatpak install -y flathub org.telegram.desktop
  when: "'org.telegram.desktop' not in telegram_installed.stdout"
  changed_when: false
