---
- name: Check if Terraform is installed
  ansible.builtin.command: terraform version
  register: terraform_installed
  failed_when: false
  changed_when: false
  check_mode: false

- name: Add HashiCorp YUM repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: "Hashicorp Stable - $basearch"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"
  when: terraform_installed.rc != 0

- name: Install Terraform
  ansible.builtin.yum:
    name: terraform
    state: present
  when: terraform_installed.rc != 0
