---
# tasks file for rocky_linux_tmux_installer

- name: Check if tmux is already installed
  ansible.builtin.command: dnf list installed tmux
  register: tmux_installed
  failed_when: tmux_installed.stderr != '' and 'No matching Packages' not in tmux_installed.stdout
  changed_when: false

- name: Install tmux
  ansible.builtin.dnf:
    name: "{{ tmux_package_name }}"
    state: present
  when: tmux_installed.rc != 0

