---
# vscode_installation/defaults/main.yml
vscode_repo_url: "https://packages.microsoft.com/yumrepos/vscode"
vscode_repo_gpg_key: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_package_name: "code"