---
- name: Check if gparted is already installed
  ansible.builtin.command: "command -v gparted"
  register: gparted_installed
  ignore_errors: true
  changed_when: false

- name: Install necessary repositories and gparted
  when: gparted_installed.rc != 0
  block:
    - name: Install EPEL repository (Extra Packages for Enterprise Linux)
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install gparted
      ansible.builtin.yum:
        name: gparted
        state: present
