---
- block:
    - name: Ensure wget and other required tools are installed
      ansible.builtin.dnf:
        name: "{{ required_packages }}"
        state: present

    - name: Download VirtualBox repository file
      ansible.builtin.get_url:
        url: "{{ virtualbox_repo_url }}"
        dest: "{{ virtualbox_repo_dest }}"
        mode: '0644'

    - name: Install VirtualBox
      ansible.builtin.dnf:
        name: "{{ virtualbox_package_name }}"
        state: present

  rescue:
    - name: Print failure message
      ansible.builtin.debug:
        msg: "Issue encountered during VirtualBox installation."
