---
- name: Install yum-utils if not present
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Configure HashiCorp YUM repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: "HashiCorp stable - $basearch"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"

- name: Install Consul
  ansible.builtin.yum:
    name: consul
    state: present
