---
- name: Install yum-utils if not present
  yum:
    name: yum-utils
    state: present

- name: Configure HashiCorp YUM repository
  yum_repository:
    name: hashicorp
    description: HashiCorp stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install Consul
  yum:
    name: consul
    state: latest
