- name: Check if linode-cli is already installed
  command: /usr/bin/pip3 list --format=freeze
  register: pip_list
  become: yes
  become_user: jay

- name: Install linode-cli using pip
  pip:
    executable: /usr/bin/pip3
    state: latest
    name: linode-cli
  become: yes
  become_user: jay
  when: "'linode-cli' not in pip_list.stdout"
  tags: packages, linode, pip, python
