---
- name: Gnome tracker clean cache
  ansible.builtin.command: tracker reset -r
  become: true
  become_user: jay
  changed_when: false

- name: Gnome tracker clean local cache
  ansible.builtin.command: tracker reset -c
  become: true
  become_user: jay
  changed_when: false
