---
- name: Add GCP CLI repository
  become: true
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/google-cloud-sdk.repo
    block: |
      [google-cloud-cli]
      name=Google Cloud CLI
      baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    create: true
    mode: '0644'
  when: gcloud_cli_installed.rc != 0

- name: Install libxcrypt-compat.x86_64 for compatibility
  become: true
  ansible.builtin.dnf:
    name: libxcrypt-compat.x86_64
    state: present

- name: Install google-cloud-cli and components
  become: true
  ansible.builtin.dnf:
    name: "{{ gcp_cli_components }}"
    state: present
  when: gcloud_cli_installed.rc != 0
