---
- name: Check if EPEL repository is enabled
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: Install EPEL release
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Steam dependencies
  ansible.builtin.yum:
    name:
      - libXScrnSaver
      - libXtst
      - alsa-lib
      - libXv
      - libXi
      - wget
    state: present

- name: Download Steam RPM package
  ansible.builtin.get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steam_latest.rpm
    dest: /tmp/steam_latest.rpm
    mode: '0644'

- name: Install Steam
  ansible.builtin.yum:
    name: /tmp/steam_latest.rpm
    state: present
