---
- name: Check if Flatpak is installed
  command: flatpak --version
  register: flatpak_installed
  ignore_errors: true

- name: Install Flatpak
  yum:
    name: flatpak
    state: present
  when: flatpak_installed is failed

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install OpenLens
  command: flatpak install --noninteractive --assumeyes flathub dev.k8slens.OpenLens
  become: true
  register: openlens_installation
  changed_when: "'Installing' in openlens_installation.stdout"

- name: Run OpenLens (Example)
  command: flatpak run --filesystem=/path/to/your/config:ro dev.k8slens.OpenLens
  become: true
  when: openlens_installation is changed
