---
- name: Check if autofs is already installed
  ansible.builtin.debug:
    msg: "autofs is already installed."
  when: "'autofs' in ansible_facts.packages"
  register: autofs_installed

- name: Install autofs package
  ansible.builtin.package:
    name: autofs
    state: present
  when: "'autofs' not in ansible_facts.packages"

- name: Ensure autofs service is started and enabled
  ansible.builtin.service:
    name: autofs
    state: started
    enabled: true
  when: autofs

- name: Copy auto.master config file
  ansible.builtin.copy:
    src: auto.master
    dest: "{{ autofs_master_config }}"
    owner: root
    group: root
    mode: '0644'
  when: autofs
  notify: restart autofs

- name: Copy auto.nfs config file
  ansible.builtin.copy:
    src: auto.nfs
    dest: "{{ autofs_nfs_config }}"
    owner: root
    group: root
    mode: '0644'
  when: autofs
  notify: restart autofs
