- name: Download RealScan G10 driver
  ansible.builtin.get_url:
    url: "{{ realscan_driver_url }}"
    dest: "{{ realscan_driver_dest }}"
    mode: '0755'

- name: Install RealScan G10 driver using Wine
  ansible.builtin.command:
    cmd: wine "{{ realscan_driver_dest }}" /S
  environment:
    WINEPREFIX: "~/.wine_realscan"
    WINEARCH: "win64"
  args:
    creates: "~/.wine_realscan/drive_c/Program Files/RealScan G10"
  become: true
  become_user: "{{ realscan_install_user }}"
