---
- name: Check if Flatpak is installed
  ansible.builtin.command: flatpak --version
  register: flatpak_installed
  ignore_errors: true
  changed_when: false

- name: Install Flatpak
  ansible.builtin.yum:
    name: flatpak
    state: present
  when: flatpak_installed.rc != 0

- name: Add Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true
  changed_when: false

- name: Install OpenLens
  ansible.builtin.command: flatpak install --noninteractive --assumeyes flathub dev.k8slens.OpenLens
  become: true
  register: openlens_installation
  changed_when: "'Installing' in openlens_installation.stdout"
  notify: Run OpenLens
