---
- name: Check if GNOME Terminal is installed
  command: which gnome-terminal
  register: gnome_terminal_installed
  failed_when: gnome_terminal_installed.rc != 0
  changed_when: false
  ignore_errors: true

- name: Create an application shortcut for GNOME Terminal on the Desktop
  copy:
    dest: "{{ ansible_env.HOME }}/Desktop/gnome-terminal.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Encoding=UTF-8
      Name={{ shortcut_name }}
      Comment={{ shortcut_comment }}
      Exec={{ shortcut_exec }}
      Icon={{ shortcut_icon }}
      Terminal=false
      Categories={{ shortcut_categories }}
  when: gnome_terminal_installed.rc == 0
  become: no
