---
- name: Install required packages for Docker
  dnf:
    name: "{{ packages[:3] }}"
    state: present

- name: Set up the Docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker Engine
  dnf:
    name: "{{ packages[3:] }}"
    state: present
    enablerepo: 'docker-ce-stable'
  when: docker_version == "latest"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
