---
# tasks file for discord_client_setup

- name: Ensure flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install Discord via Flatpak
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
    method: system
    remote: flathub
  become: true
