---
- name: Ensure dconf-cli is installed (Rocky Linux 9)
  ansible.builtin.dnf:
    name: dconf-cli
    state: present
  become: true

- name: gnome | tracker | disable indexing while running on battery
  tags: gnome,tracker
  become: true
  become_user: jay
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/index-on-battery"
    value: "false"

- name: gnome | tracker | set ignored directories
  tags: gnome,tracker
  become: true
  become_user: jay
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/ignored-directories"
    value: "['po', 'CVS', 'core-dumps', '/home/jay/downloads', 'lost+found', '/mnt/freenas']"

