---
- name: Check for installed GNOME packages
  ansible.builtin.yum:
    list: gnome-shell
  register: gnome_packages

  loop:
    - gedit
    - gnome-backgrounds
    - gnome-boxes
    - gnome-control-center
    - gnome-icon-theme
    - gnome-power-manager
    - gnome-remote-desktop
    - gnome-shell
    - gnome-shell-extensions
    - gnome-system-monitor
    - gnome-terminal
    - gnome-todo
    - gnome-tweaks
    - nautilus
    - gnome-software-plugin-flatpak
  changed_when: false

- name: Install GNOME packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_check.results | selectattr('rc', 'defined') | map(attribute='item') }}"
  when: pkg_check is defined and pkg_check.results | length > 0

- name: Ensure the GNOME Display Manager (GDM) is enabled and running
  ansible.builtin.service:
    name: gdm
    state: started
    enabled: true
