---
- name: Setup Rocky Linux 9 Workstation
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    # System Setup
    - name: System Setup Tasks
      block:
        - ansible.builtin.import_role:
            name: system_setup/ssh_hardening

    # Users
    - name: User Configuration
      block:
        - ansible.builtin.import_role:
            name: users/rocky_linux_user_setup

    # Install Software
    - name: Install Software Packages
      block:
        - ansible.builtin.import_role:
            name: software/android_studio_setup
        - ansible.builtin.import_role:
            name: software/boundary_role
        - ansible.builtin.import_role:
            name: software/docker_setup_configuration
        - ansible.builtin.import_role:
            name: software/gparted_role
        - ansible.builtin.import_role:
            name: software/install_minikube
        - ansible.builtin.import_role:
            name: software/my_boto_role
        - ansible.builtin.import_role:
            name: software/realscan_g10_install
        - ansible.builtin.import_role:
            name: software/telegram_install
        - ansible.builtin.import_role:
            name: software/virtualbox_setup_configuration
        - ansible.builtin.import_role:
            name: software/audacious_install
        - ansible.builtin.import_role:
            name: software/caffeine_install
        - ansible.builtin.import_role:
            name: software/epel_wine_setup
        - ansible.builtin.import_role:
            name: software/firefox_installation
        - ansible.builtin.import_role:
            name: software/install_signal_desktop
        - ansible.builtin.import_role:
            name: software/my_lens_role
        - ansible.builtin.import_role:
            name: software/rocky_consul_install
        - ansible.builtin.import_role:
            name: software/terraform_installer
        - ansible.builtin.import_role:
            name: software/thunderbird_installation
        - ansible.builtin.import_role:
            name: software/vscode_setup_configuration
        - ansible.builtin.import_role:
            name: software/aws_cli_installation
        - ansible.builtin.import_role:
            name: software/civu_cli
        - ansible.builtin.import_role:
            name: software/conda_installation
        - ansible.builtin.import_role:
            name: software/gcloud_cli
        - ansible.builtin.import_role:
            name: software/kindle_for_pc
        - ansible.builtin.import_role:
            name: software/my_nomad_role
        - ansible.builtin.import_role:
            name: software/notion_setup
        - ansible.builtin.import_role:
            name: software/rocky_linux_tmux_installer
        - ansible.builtin.import_role:
            name: software/software_vlc
        - ansible.builtin.import_role:
            name: software/todoist_installation
        - ansible.builtin.import_role:
            name: software/zoom_installation
        - ansible.builtin.import_role:
            name: software/azure_cli_install
        - ansible.builtin.import_role:
            name: software/bentoml_install
        - ansible.builtin.import_role:
            name: software/digitalocean_cli
        - ansible.builtin.import_role:
            name: software/git_setup_and_configuration
        - ansible.builtin.import_role:
            name: software/linode_cli
        - ansible.builtin.import_role:
            name: software/mamba_installation
        - ansible.builtin.import_role:
            name: software/nvidia_driver_setup
        - ansible.builtin.import_role:
            name: software/packer_install
        - ansible.builtin.import_role:
            name: software/spotify_setup
        - ansible.builtin.import_role:
            name: software/steam_install
        - ansible.builtin.import_role:
            name: software/vagrant_installer
        - ansible.builtin.import_role:
            name: software/vault_installation
        - ansible.builtin.import_role:
            name: software/blender_install
        - ansible.builtin.import_role:
            name: software/discord_client_setup
        - ansible.builtin.import_role:
            name: software/waypoint
