- name: Ensure Firefox distribution directory exists on Rocky Linux
  ansible.builtin.file:
    path: "/usr/lib/firefox/distribution"
    state: directory
    mode: '0755'
  become: yes  # Ensures the task is run with elevated privileges, necessary for modifying system directories

- name: Deploy Firefox policies for extension installation on Rocky Linux
  ansible.builtin.copy:
    src: "files/policies.json"  # Assumes this file is present in your Ansible project under the "files" directory
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: '0644'
  become: yes  # Similar to above, requires elevated privileges to write to the system directory
